title: Patrick McCarthy
subtitle: ""
  #email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://patrickmccarthy.cc" # the base hostname & protocol for your site, e.g. http://example.com
  #twitter_username: jekyllrb
github_username:  asteriske 
repository: "asteriske/asteriske.github.io"

locale: "en-US"
author:
  #name     : "Your Name"
  avatar   : "/assets/images/bio-photo.png"
  location : "New York, NY"
  bio      : "I'm Patrick. I'm a data scientist with an IT background who loves working on the whole stack, walking places and finding interesting things to eat off the beaten path. Before coming to New York City I lived, worked and studied in Los Angeles and Boston."
  links:
  - label: "GitHub"
    icon: "fab fa-fw fa-github-square"
    url: "https://github.com/asteriske"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "dark"

plugins:
  #  - jekyll-feed
  - jekyll-include-cache

include: 
  - "_pages"
  - "_projects"
exclude: ['.git']

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      mathjax: true

  # _projects
  - scope:
      path: ""
      type: projects 
    values:
      layout: single
      author_profile: false
      share: true

collections:
  projects:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

head_scripts:
  - /assets/js/mathjax/tex-mml-chtml.js 

paginate_path: /blog/page:num

atom_feed:
  hide: true
